export const categoryMap = {
  'domesticos': 'domésticos',
  'eletrico': 'elétrico',
  'manutencao': 'manutenção',
  'administracao': 'administração',
  'consultoria': 'consultoria',
  'contabilidade': 'contabilidade',
  'design': 'design',
  'engenharia': 'engenharia',
  'Data Entry': 'Data Entry',
  'Social Media Management': 'Social Media Management',
  'juridico': 'jurídico',
  'marketing': 'marketing',
  'saude': 'saúde',
  'tecnologia': 'tecnologia',
  'transporte': 'transporte',
  'vendas': 'vendas',
  'fotografia': 'fotografia',
  'musica': 'música',
  'educacao': 'educação',
  'idiomas': 'idiomas',
  'esportes': 'esportes',
  'culinaria': 'culinária',
  'beleza': 'beleza',
  'moda': 'moda',
  'artesanato': 'artesanato',
};
